=== LarhzalOthmane/XML-tutorial-command/command.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT command (client, (commandLine)+)>
<!ATTLIST command date CDATA #REQUIRED >
<!ELEMENT client (firstName, lastName, adresse, phoneNumber) >
<!ELEMENT firstName (#PCDATA) >
<!ELEMENT lastName (#PCDATA) >
<!ELEMENT phoneNumber (#PCDATA) >

<!ELEMENT adresse (street, appartement, district, city, country) >
<!ELEMENT street (#PCDATA) >
<!ELEMENT appartement (#PCDATA) >
<!ELEMENT district (#PCDATA) >
<!ELEMENT city (#PCDATA) >
<!ELEMENT country (#PCDATA) >

<!ELEMENT commandLine (product, quantity)+>
<!ELEMENT product (title, category) >
<!ATTLIST product id ID #REQUIRED>
<!ELEMENT title (#PCDATA) >
<!ELEMENT category (#PCDATA) >

<!ELEMENT quantity EMPTY >
<!ATTLIST quantity product IDREF #REQUIRED>
<!ATTLIST quantity value CDATA #REQUIRED>

=== LarhzalOthmane/XML-tutorial-command/command.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE command SYSTEM "command.dtd">
<command date="10/28/2020">
    <client>
        <firstName>Titoss</firstName>
        <lastName>Larhzal</lastName>
        <adresse>
            <street>EL Massira</street>
            <appartement>120</appartement>
            <district>Hay Riad</district>
            <city>Meknes</city>
            <country>Morocco</country>
        </adresse>
        <phoneNumber>+212682251070</phoneNumber>
    </client>
    <commandLine>
        <product id="GN20">
            <title>Galaxy Note 20+</title>
            <category>Smartphone</category>
        </product>
        <quantity product="GN20" value="1"/>
    </commandLine>
    <commandLine>
        <product id="GS20">
            <title>Galaxy S20</title>
            <category>Smartphone</category>
        </product>
        <quantity product="GS20" value="1"/>
    </commandLine>
</command>
